Repository bcgov/react-shared-components, pull requests merged in 2020-07, with the labels that each got.

#3 Update README.md
  README.md
Labels: documentation

#5 Add callout component
  package.json
  src/components/callout/Callout.css
  src/components/callout/Callout.js
  src/components/callout/Callout.mdx
  src/components/callout/Callout.stories.js
  src/components/callout/Callout.test.js
  src/components/callout/__snapshots__/Callout.stories.storyshot
  src/components/callout/__snapshots__/Callout.test.js.snap
Labels: enhancement

#6 fix issue of not exporting component
  package.json
  src/index.js
Labels: bug, enhancement

#10 Update build to only docs
  package.json
Labels: documentation

#16 Adding Jest test action
  .github/dependabot.yml
  .github/workflows/test-runner.yml
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.stories.storyshot
Labels: Tests

#14 Add radio button component
  package.json
  src/components/radio/Radio.css
  src/components/radio/Radio.js
  src/components/radio/Radio.mdx
  src/components/radio/Radio.stories.js
  src/components/radio/Radio.test.js
  src/components/radio/__snapshots__/Radio.stories.storyshot
  src/components/radio/__snapshots__/Radio.test.js.snap
Labels: enhancement

#17 Add dropdown component!!
  src/components/dropdown/Dropdown.css
  src/components/dropdown/Dropdown.js
  src/components/dropdown/Dropdown.mdx
  src/components/dropdown/Dropdown.stories.js
  src/components/dropdown/Dropdown.test.js
  src/components/dropdown/__snapshots__/Dropdown.stories.storyshot
  src/components/dropdown/__snapshots__/Dropdown.test.js.snap
  src/components/radio/__snapshots__/Radio.stories.storyshot
  src/components/radio/__snapshots__/Radio.test.js.snap
Labels: enhancement

#15 Update: Table
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.stories.storyshot
  src/components/display-box/__snapshots__/DisplayBox.stories.storyshot
  src/components/display-box/__snapshots__/DisplayBox.test.js.snap
  src/components/table/Table.css
  src/components/table/Table.js
  src/components/table/Table.stories.js
  src/components/table/Table.test.js
  src/components/table/__snapshots__/Table.stories.storyshot
  src/components/table/__snapshots__/Table.test.js.snap
Labels: enhancement

#28 Update: Table css
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.stories.storyshot
  src/components/display-box/DisplayBox.stories.js
  src/components/display-box/__snapshots__/DisplayBox.stories.storyshot
  src/components/display-box/__snapshots__/DisplayBox.test.js.snap
  src/components/table/Table.css
  src/components/table/Table.js
  src/components/table/__snapshots__/Table.stories.storyshot
  src/components/table/__snapshots__/Table.test.js.snap
Labels: bug, enhancement

#30 Fill avail width for table keys
  package.json
  src/components/table/Table.css
Labels: bug, enhancement

#31 fix styling issue
  src/components/table/Table.css
Labels: bug
