Repository bcgov/react-shared-components, pull requests merged in 2020-09, with the labels that each got.

#143 Stylefix for mozilla and ms
  package.json
  src/components/table/Table.css
Labels: bug

#148 Fix table mdx documentation
  src/components/table/Table.mdx
Labels: bug, documentation, enhancement

#149 minor fix/update to documentation
  src/components/table/Table.mdx
Labels: documentation

#152 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#155 update storybook packages to latest
  package.json
  yarn.lock
Labels: dependencies, enhancement

#159 Create code-climate-test-coverage.yaml
  .github/workflows/code-climate-test-coverage.yaml
Labels: code climate, git action

#158 Cleanup code climate issues
  .github/workflows/test-runner.yml
  src/components/confirmation-popup/ConfirmationPopup.stories.js
  src/components/confirmation-popup/ConfirmationPopup.test.js
  src/components/header/Header.test.js
  src/components/terms-of-use/TermsOfUse.test.js
  src/modules/confirmationPopupTestData.js
Labels: Tests, code climate, enhancement

#160 more cleanup improving maintainability
  README.md
  package.json
  src/components/date-pick/DatePick.stories.js
Labels: code climate, enhancement, git action

#162 Fix more code climate issues
  src/components/button/Button.test.js
Labels: code climate, enhancement

#163 More code climate fixes
  src/components/terms-of-use/TermsOfUse.stories.js
Labels: Tests, code climate, enhancement

#164 refactoring
  src/components/display-box/DisplayBox.test.js
Labels: code climate, enhancement, git action

#165 refactor confirmation popup
  src/components/confirmation-popup/ConfirmationPopup.js
Labels: code climate, enhancement

#176 🤖 Dependabots assemble
  package.json
  yarn.lock
Labels: dependencies

#177 Fix accessibility issues
  .eslintrc.js
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.stories.storyshot
  src/components/date-pick/__snapshots__/DatePick.stories.storyshot
  src/components/footer/Footer.js
  src/components/footer/__snapshots__/Footer.stories.storyshot
  src/components/footer/__snapshots__/Footer.test.js.snap
  src/components/header/Header.js
  src/components/header/__snapshots__/Header.stories.storyshot
  src/components/header/__snapshots__/Header.test.js.snap
Labels: bug, enhancement

#178 Update package.json version for release
  package.json
Labels: enhancement

#179 Add id to sidecard component
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.stories.storyshot
  src/components/date-pick/__snapshots__/DatePick.stories.storyshot
  src/components/sidecard/Sidecard.js
  src/components/sidecard/Sidecard.stories.js
  src/components/sidecard/Sidecard.test.js
  src/components/sidecard/__snapshots__/Sidecard.stories.storyshot
  src/components/sidecard/__snapshots__/Sidecard.test.js.snap
Labels: enhancement

#180 Update package.json version for release 0.5.9
  package.json
Labels: enhancement

#186 🤖 Transformers, dependabots in disguise
  package.json
  yarn.lock
Labels: dependencies
