Repository bcgov/react-shared-components, pull requests merged in 2020-08, with the labels that each got.

#58 Sidecard styling update
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.stories.storyshot
  src/components/sidecard/Sidecard.css
  src/components/sidecard/Sidecard.js
  src/components/sidecard/__snapshots__/Sidecard.stories.storyshot
  src/components/sidecard/__snapshots__/Sidecard.test.js.snap
Labels: enhancement

#61 Fix mobile styling for button/confirmation popup
  package.json
  src/components/button/Button.css
  src/components/button/Button.js
  src/components/button/__snapshots__/Button.stories.storyshot
  src/components/button/__snapshots__/Button.test.js.snap
  src/components/confirmation-popup/ConfirmationPopup.css
  src/components/confirmation-popup/ConfirmationPopup.js
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.test.js.snap
  src/components/terms-of-use/TermsOfUse.css
Labels: enhancement

#62 Remove div from button
  package.json
  src/components/button/Button.js
  src/components/button/__snapshots__/Button.stories.storyshot
  src/components/button/__snapshots__/Button.test.js.snap
  src/components/confirmation-popup/ConfirmationPopup.js
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.test.js.snap
Labels: bug, enhancement

#77 📅 Add datepicker component
  package.json
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.stories.storyshot
  src/components/date-pick/DatePick.css
  src/components/date-pick/DatePick.js
  src/components/date-pick/DatePick.mdx
  src/components/date-pick/DatePick.stories.js
  src/components/date-pick/DatePick.test.js
  src/components/date-pick/__snapshots__/DatePick.stories.storyshot
  src/components/date-pick/__snapshots__/DatePick.test.js.snap
  src/index.js
  src/storyshots.test.js
  yarn.lock
Labels: enhancement

#83 Add label and asterisk to textarea and datepicker
  package.json
  src/components/date-pick/DatePick.js
  src/components/date-pick/DatePick.mdx
  src/components/date-pick/DatePick.stories.js
  src/components/date-pick/DatePick.test.js
  src/components/date-pick/__snapshots__/DatePick.test.js.snap
  src/components/textarea/Textarea.js
  src/components/textarea/Textarea.mdx
  src/components/textarea/__snapshots__/Textarea.stories.storyshot
  src/components/textarea/__snapshots__/Textarea.test.js.snap
Labels: enhancement

#84 fixes to styling of textarea label
  package.json
  src/components/textarea/Textarea.css
  src/components/textarea/Textarea.js
  src/components/textarea/Textarea.test.js
  src/components/textarea/__snapshots__/Textarea.stories.storyshot
  src/components/textarea/__snapshots__/Textarea.test.js.snap
Labels: bug, enhancement

#85 fix storybook issues and test coverage issues
  .storybook/main.js
  package.json
  src/components/alert/Alert.stories.js
  src/components/button/Button.stories.js
  src/components/callout/Callout.stories.js
  src/components/confirmation-popup/ConfirmationPopup.stories.js
  src/components/date-pick/DatePick.stories.js
  src/components/display-box/DisplayBox.stories.js
  src/components/dropdown/Dropdown.stories.js
  src/components/footer/Footer.stories.js
  src/components/header/Header.stories.js
  src/components/input/Input.stories.js
  src/components/loader/Loader.stories.js
  src/components/radio/Radio.stories.js
  src/components/sidecard/Sidecard.stories.js
  src/components/table/Table.stories.js
  src/components/terms-of-use/TermsOfUse.stories.js
  src/components/textarea/Textarea.stories.js
Labels: enhancement

#86 Add loader to button and fix snapshot issue with date
  src/components/button/Button.css
  src/components/button/Button.js
  src/components/button/Button.mdx
  src/components/button/Button.stories.js
  src/components/button/Button.test.js
  src/components/button/__snapshots__/Button.stories.storyshot
  src/components/button/__snapshots__/Button.test.js.snap
  src/components/confirmation-popup/__snapshots__/ConfirmationPopup.test.js.snap
  src/components/date-pick/DatePick.test.js
  src/components/date-pick/__snapshots__/DatePick.test.js.snap
  src/components/loader/Loader.js
  src/components/loader/__snapshots__/Loader.stories.storyshot
  src/components/loader/__snapshots__/Loader.test.js.snap
Labels: enhancement

#92 Add getting started to readme
  README.md
Labels: documentation, enhancement

#94 Update README
  README.md
Labels: documentation

#100 Dependabot/npm and yarn/storybook/addon storyshots 6.0.12
  package.json
  yarn.lock
Labels: enhancement

#125 update api docs for callout component
  src/components/callout/Callout.mdx
Labels: documentation, enhancement
